apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  acme:
    email: {{ .Values.acmeEmail }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: production-issuer-account-key
    solvers:
      {{- if eq .Values.validation.type "dns" }}
      - dns01:
          cloudDNS:
            project: {{ .Values.project }}
      {{- else }}
      - http01:
          ingress:
            class: {{ .Values.validation.ingressClass }}
      {{- end }}
