---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-credentials
spec:
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: grafana-credentials
    deletionPolicy: "Retain"
  data:
    - secretKey: admin-user
      remoteRef:
        key: grafana-credentials
        property: admin-user
    - secretKey: admin-password
      remoteRef:
        key: grafana-credentials
        property: admin-password
