apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-nginx-iap
spec:
  dnsNames:
    {{- range .Values.hosts }}
    - {{ . }}
    {{- end }}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
  secretName: iap-tls
