apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gcp-external-iap-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store
  target:                                                             
    name: iap-secret
    creationPolicy: Owner
  data:
  - secretKey: client_secret
    remoteRef:
      key: {{ .Values.iapConfig.secret }}
  - secretKey: client_id
    remoteRef:
      key: {{ .Values.iapConfig.id }}
