{{- if eq .Values.loadBalancerType "L7" }}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: ingress-nginx-controller
spec:
  healthCheck:
    requestPath: /healthz
    {{- if .Values.tlsSecret }}
    type: HTTPS
    {{- else }}
    type: HTTP
    {{- end }}
{{- if .Values.tlsSecret }}
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: ingress-nginx-controller
spec:
  redirectToHttps:
    enabled: true
  sslPolicy: modern
{{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx-controller
  annotations:
    kubernetes.io/ingress.class: gce
    {{- if .Values.loadBalancerIPName }}
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.loadBalancerIPName }}
    {{- end }}
    {{- if .Values.tlsSecret }}
    ingress.kubernetes.io/ssl-redirect: "true"
    networking.gke.io/v1beta1.FrontendConfig: ingress-nginx-controller
    {{- end }}
spec:
  defaultBackend:
    service:
      name: ingress-nginx-controller
      port:
        {{- if .Values.tlsSecret }}
        name: https
        {{- else }}
        name: http
        {{- end }}
  {{- if .Values.tlsSecret }}
  tls:
  - secretName: {{ .Values.tlsSecret }}
  {{- end }}
{{- end }}
