apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: cert-manager
    name: in-cluster
  source:
    # ✏️ Your repository URL
    repoURL: git@github.com:PierrickChp/library-k8s.git
    targetRevision: HEAD
    path: helm/cert-manager/
    helm:
      valueFiles:
        - "values.yaml"
        # ✏️ Add "values.dns.yaml" to use cert-manager with dns validation
        - "values.dns.yaml"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
