apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: ingress-nginx
    name: in-cluster
  source:
    # ✏️ Your repository URL
    repoURL: git@github.com:padok-team/library-kubernetes-gcp-starter.git
    targetRevision: HEAD
    path: helm/ingress-nginx/
    helm:
      valueFiles:
        - "values.yaml"
        # ✏️ Add "values.L7.yaml" to deploy a L7 load balancer
        # - "values.L7.yaml"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
