apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: oauth2-proxy
    name: in-cluster
  source:
    # ✏️ Your repository URL
    repoURL: git@github.com:PierrickChp/library-k8s.git
    targetRevision: HEAD
    path: helm/oauth2-proxy/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
