apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secret-store
  annotations:
    "helm.sh/hook": post-install
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.projectID }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.clusterLocation }}
          clusterName: {{ .Values.clusterName }}
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
