apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-repository-credentials
  annotations:
    "helm.sh/hook": pre-install
spec:
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: argocd-repository-credentials
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        url: {{ .Values.repoURL }}
        sshPrivateKey: '{{ "{{ .sshPrivateKey | toString }}" }}'
  data:
    - secretKey: sshPrivateKey
      remoteRef:
        key: argocd-repository-credentials
